BackgrounderJobId,Class,File,Line,Message,Severity,Site,Thread,Timestamp
,com.tableausoftware.newrelic.jmx.JMXClient,backgrounder_node1-0.log,173,"Exception in loading app_name from Newrelic.yml file, NR thread interruptted: null",ERROR,,scheduled-pending-search-items-recover-1,08/09/2019 20:38:32
,com.tableausoftware.newrelic.jmx.JMXClient,backgrounder_node1-0.log,174,Exception while loading: null,ERROR,,scheduled-pending-search-items-recover-1,08/09/2019 20:38:32
,com.tableausoftware.newrelic.jmx.JMXClient,backgrounder_node1-0.log,175,CachedSupplier is empty.,ERROR,,scheduled-pending-search-items-recover-1,08/09/2019 20:38:32
1,com.tableausoftware.backgrounder.runner.BackgroundJobRunner,backgrounder_node1-0.log,259,"Error executing background job: SanitizeDataServerWorkbooks
java.util.concurrent.ExecutionException: java.util.NoSuchElementException: Reading non-existent java.lang.Boolean key: features.WorkbookSanitizer
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeNextJob_aroundBody2(BackgroundJobRunner.java:279)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$AjcClosure3.run(BackgroundJobRunner.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeNextJob(BackgroundJobRunner.java:216)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeJobs_aroundBody0(BackgroundJobRunner.java:201)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$AjcClosure1.run(BackgroundJobRunner.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeJobs(BackgroundJobRunner.java:177)
	at com.tableausoftware.backgrounder.config.BackgroundJobRunnerSchedulingConfig.lambda$scheduleTask$0(BackgroundJobRunnerSchedulingConfig.java:42)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.NoSuchElementException: Reading non-existent java.lang.Boolean key: features.WorkbookSanitizer
	at com.tableausoftware.core.configuration.spring.AppConfigSpringEnvironmentAdapter.getRequiredProperty(AppConfigSpringEnvironmentAdapter.java:178)
	at com.tableausoftware.core.configuration.spring.AppConfigSpringEnvironmentAdapter.getBool(AppConfigSpringEnvironmentAdapter.java:81)
	at com.tableausoftware.model.workgroup.workers.SanitizeDataServerWorkbooksWorker.execute_aroundBody2(SanitizeDataServerWorkbooksWorker.java:89)
	at com.tableausoftware.model.workgroup.workers.SanitizeDataServerWorkbooksWorker$AjcClosure3.run(SanitizeDataServerWorkbooksWorker.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.model.workgroup.workers.SanitizeDataServerWorkbooksWorker.execute(SanitizeDataServerWorkbooksWorker.java:89)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable.executeWithWorker(BackgroundJobRunner.java:804)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable.call_aroundBody0(BackgroundJobRunner.java:763)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable$AjcClosure1.run(BackgroundJobRunner.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable.call(BackgroundJobRunner.java:758)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable.call(BackgroundJobRunner.java:745)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more",ERROR,,scheduled-background-job-runner-1,08/09/2019 20:39:14
75,com.tableausoftware.backgrounder.runner.BackgroundJobRunner,backgrounder_node1-0.log,932,"Error executing background job: ReapFlowEvents
java.util.concurrent.ExecutionException: javax.persistence.TransactionRequiredException: Executing an update/delete query
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeNextJob_aroundBody2(BackgroundJobRunner.java:279)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$AjcClosure3.run(BackgroundJobRunner.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeNextJob(BackgroundJobRunner.java:216)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeJobs_aroundBody0(BackgroundJobRunner.java:201)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$AjcClosure1.run(BackgroundJobRunner.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeJobs(BackgroundJobRunner.java:177)
	at com.tableausoftware.backgrounder.config.BackgroundJobRunnerSchedulingConfig.lambda$scheduleTask$0(BackgroundJobRunnerSchedulingConfig.java:42)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.persistence.TransactionRequiredException: Executing an update/delete query
	at org.hibernate.jpa.spi.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:375)
	at com.sun.proxy.$Proxy168.executeUpdate(Unknown Source)
	at com.tableausoftware.domain.content.flows.jpa.FlowEventDaoJpa.deleteByCreationDate(FlowEventDaoJpa.java:69)
	at com.tableausoftware.domain.content.flows.FlowEventManager.deleteFlowEvents(FlowEventManager.java:58)
	at com.tableausoftware.domain.content.flows.FlowService.reapFlowEvents(FlowService.java:365)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tableausoftware.core.spring.DelayedInstantiationHandler$LazyInitInvocationHandler.invoke(DelayedInstantiationHandler.java:189)
	at com.sun.proxy.$Proxy124.reapFlowEvents(Unknown Source)
	at com.tableausoftware.model.workgroup.workers.ReapFlowEventsWorker.execute_aroundBody0(ReapFlowEventsWorker.java:67)
	at com.tableausoftware.model.workgroup.workers.ReapFlowEventsWorker$AjcClosure1.run(ReapFlowEventsWorker.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.model.workgroup.workers.ReapFlowEventsWorker.execute(ReapFlowEventsWorker.java:61)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable.executeWithWorker(BackgroundJobRunner.java:804)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable.call_aroundBody0(BackgroundJobRunner.java:763)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable$AjcClosure1.run(BackgroundJobRunner.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable.call(BackgroundJobRunner.java:758)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable.call(BackgroundJobRunner.java:745)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more",ERROR,,scheduled-background-job-runner-1,08/09/2019 20:39:37
,com.tableausoftware.newrelic.jmx.JMXClient,backgrounder_node1-0.log,2774,"Exception in loading app_name from Newrelic.yml file, NR thread interruptted: null",ERROR,,scheduled-schedule-runner-1,08/09/2019 21:40:03
,com.tableausoftware.newrelic.jmx.JMXClient,backgrounder_node1-0.log,2775,Exception while loading: null,ERROR,,scheduled-schedule-runner-1,08/09/2019 21:40:03
,com.tableausoftware.newrelic.jmx.JMXClient,backgrounder_node1-0.log,2776,CachedSupplier is empty.,ERROR,,scheduled-schedule-runner-1,08/09/2019 21:40:03
209,com.tableausoftware.model.workgroup.workers.GenerateThumbnailsWorker,backgrounder_node1-0.log,3269,Thumbnail generation failed for workbook: Large2 repositoryUrl: Large2 jobId: 209,ERROR,Default,pool-12-thread-1,08/09/2019 21:57:48
209,com.tableausoftware.backgrounder.runner.BackgroundJobRunner,backgrounder_node1-0.log,3270,"Error executing background job: GenerateThumbnails
java.util.concurrent.ExecutionException: com.tableausoftware.nativeapi.exceptions.TableauException: There is not enough memory to display the 3603031 rows and 1 columns in this view. To enable the view, remove fields from the Rows and Columns or filter the data.

	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeNextJob_aroundBody2(BackgroundJobRunner.java:279)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$AjcClosure3.run(BackgroundJobRunner.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeNextJob(BackgroundJobRunner.java:216)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeJobs_aroundBody0(BackgroundJobRunner.java:201)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$AjcClosure1.run(BackgroundJobRunner.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeJobs(BackgroundJobRunner.java:177)
	at com.tableausoftware.backgrounder.config.BackgroundJobRunnerSchedulingConfig.lambda$scheduleTask$0(BackgroundJobRunnerSchedulingConfig.java:42)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.tableausoftware.nativeapi.exceptions.TableauException: There is not enough memory to display the 3603031 rows and 1 columns in this view. To enable the view, remove fields from the Rows and Columns or filter the data.

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.tableausoftware.nativeapi.serialization.ExceptionMapper.mapTableauException(ExceptionMapper.java:111)
	at com.tableausoftware.nativeapi.serialization.ExceptionMapper.mapVizqlWorkerException(ExceptionMapper.java:57)
	at com.tableausoftware.nativeapi.serialization.ExceptionMapper.mapVizqlWorkerException(ExceptionMapper.java:74)
	at com.tableausoftware.nativeapi.dll.NativeApiJNI.VQLSessionPtr_ComputeView(Native Method)
	at com.tableausoftware.nativeapi.dll.VQLSessionPtr.ComputeView(VQLSessionPtr.java:280)
	at com.tableausoftware.model.workgroup.service.VqlSessionService$VqlSessionAction.refreshThumbnailsForWorkbook(VqlSessionService.java:1318)
	at com.tableausoftware.model.workgroup.service.VqlSessionService$VqlSessionAction.access$800(VqlSessionService.java:1065)
	at com.tableausoftware.model.workgroup.service.VqlSessionService.refreshThumbnailsForWorkbook(VqlSessionService.java:517)
	at com.tableausoftware.model.workgroup.workers.GenerateThumbnailsWorker.executeWithDataengine_aroundBody0(GenerateThumbnailsWorker.java:101)
	at com.tableausoftware.model.workgroup.workers.GenerateThumbnailsWorker$AjcClosure1.run(GenerateThumbnailsWorker.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.model.workgroup.workers.GenerateThumbnailsWorker.executeWithDataengine(GenerateThumbnailsWorker.java:81)
	at com.tableausoftware.model.workgroup.workers.DataengineDependentWorker.execute(DataengineDependentWorker.java:87)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable.executeWithWorker(BackgroundJobRunner.java:811)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable.call_aroundBody0(BackgroundJobRunner.java:763)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable$AjcClosure1.run(BackgroundJobRunner.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable.call(BackgroundJobRunner.java:758)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable.call(BackgroundJobRunner.java:745)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more",ERROR,Default,scheduled-background-job-runner-1,08/09/2019 21:57:48
,com.tableausoftware.newrelic.jmx.JMXClient,backgrounder_node1-1.log,174,"Exception in loading app_name from Newrelic.yml file, NR thread interruptted: null",ERROR,,scheduled-background-job-runner-1,08/09/2019 20:38:35
,com.tableausoftware.newrelic.jmx.JMXClient,backgrounder_node1-1.log,175,Exception while loading: null,ERROR,,scheduled-background-job-runner-1,08/09/2019 20:38:35
,com.tableausoftware.newrelic.jmx.JMXClient,backgrounder_node1-1.log,176,CachedSupplier is empty.,ERROR,,scheduled-background-job-runner-1,08/09/2019 20:38:35
,org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler,backgrounder_node1-1.log,906,"Unexpected error occurred in scheduled task.
javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: Could not open connection
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
	at org.hibernate.jpa.internal.QueryImpl.getSingleResult(QueryImpl.java:524)
	at sun.reflect.GeneratedMethodAccessor128.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:375)
	at com.sun.proxy.$Proxy168.getSingleResult(Unknown Source)
	at com.tableausoftware.core.configuration.jpa.GlobalSettingDaoJpa.isSettingLaterThanNow(GlobalSettingDaoJpa.java:90)
	at com.tableausoftware.core.configuration.service.GlobalSettingService.isSettingLaterThanNow(GlobalSettingService.java:236)
	at com.tableausoftware.core.configuration.service.GlobalSettingService$$FastClassBySpringCGLIB$$8b611f6.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:667)
	at com.tableausoftware.core.configuration.service.GlobalSettingService$$EnhancerBySpringCGLIB$$57b08afb.isSettingLaterThanNow(<generated>)
	at com.tableausoftware.backgrounder.runner.ScheduleRunner.runScheduledTasks(ScheduleRunner.java:160)
	at com.tableausoftware.backgrounder.config.ScheduleRunnerSchedulingConfig$1.run_aroundBody0(ScheduleRunnerSchedulingConfig.java:45)
	at com.tableausoftware.backgrounder.config.ScheduleRunnerSchedulingConfig$1$AjcClosure1.run(ScheduleRunnerSchedulingConfig.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.backgrounder.config.ScheduleRunnerSchedulingConfig$1.run(ScheduleRunnerSchedulingConfig.java:45)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.exception.JDBCConnectionException: Could not open connection
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:132)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:235)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.getConnection(LogicalConnectionImpl.java:171)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:63)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:162)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:186)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:160)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1884)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1861)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1838)
	at org.hibernate.loader.Loader.doQuery(Loader.java:909)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:354)
	at org.hibernate.loader.Loader.doList(Loader.java:2553)
	at org.hibernate.loader.Loader.doList(Loader.java:2539)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2369)
	at org.hibernate.loader.Loader.list(Loader.java:2364)
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:353)
	at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:1873)
	at org.hibernate.internal.AbstractSessionImpl.list(AbstractSessionImpl.java:311)
	at org.hibernate.internal.SQLQueryImpl.list(SQLQueryImpl.java:141)
	at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:573)
	at org.hibernate.jpa.internal.QueryImpl.getSingleResult(QueryImpl.java:495)
	... 26 more
Caused by: org.postgresql.util.PSQLException: Connection to localhost:8060 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:280)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:454)
	at org.postgresql.Driver.connect(Driver.java:256)
	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:39)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:256)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at org.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:134)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1533)
	at com.tableausoftware.config.WorkgroupRoutingDataSource.getConnection(WorkgroupRoutingDataSource.java:95)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:139)
	at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:380)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:228)
	... 46 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.postgresql.core.PGStream.<init>(PGStream.java:70)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:91)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	... 61 more",ERROR,,scheduled-schedule-runner-1,08/09/2019 21:29:37
,org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler,backgrounder_node1-1.log,998,"Unexpected error occurred in scheduled task.
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: Could not open connection
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:431)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:377)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:461)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:277)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:70)
	at com.tableausoftware.core.search.impl.PendingSearchItemsService.getPendingSearchUpdateEntity(PendingSearchItemsService.java:235)
	at com.tableausoftware.core.search.impl.PendingSearchItemsService.recoverUnexecutedPendingUpdates_aroundBody0(PendingSearchItemsService.java:155)
	at com.tableausoftware.core.search.impl.PendingSearchItemsService$AjcClosure1.run(PendingSearchItemsService.java:1)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:66)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:72)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:70)
	at com.tableausoftware.core.search.impl.PendingSearchItemsService.recoverUnexecutedPendingUpdates(PendingSearchItemsService.java:145)
	at com.tableausoftware.backgrounder.config.PendingSearchUpdatesSchedulingConfig$1.run_aroundBody0(PendingSearchUpdatesSchedulingConfig.java:48)
	at com.tableausoftware.backgrounder.config.PendingSearchUpdatesSchedulingConfig$1$AjcClosure1.run(PendingSearchUpdatesSchedulingConfig.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.backgrounder.config.PendingSearchUpdatesSchedulingConfig$1.run(PendingSearchUpdatesSchedulingConfig.java:48)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: Could not open connection
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:1771)
	at org.hibernate.jpa.internal.TransactionImpl.begin(TransactionImpl.java:64)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:189)
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:380)
	... 26 more
Caused by: org.hibernate.exception.JDBCConnectionException: Could not open connection
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:132)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:235)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.getConnection(LogicalConnectionImpl.java:171)
	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.doBegin(JdbcTransaction.java:67)
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.begin(AbstractTransactionImpl.java:162)
	at org.hibernate.internal.SessionImpl.beginTransaction(SessionImpl.java:1435)
	at org.hibernate.jpa.internal.TransactionImpl.begin(TransactionImpl.java:61)
	... 28 more
Caused by: org.postgresql.util.PSQLException: Connection to localhost:8060 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:280)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:454)
	at org.postgresql.Driver.connect(Driver.java:256)
	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:39)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:256)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at org.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:134)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1533)
	at com.tableausoftware.config.WorkgroupRoutingDataSource.getConnection(WorkgroupRoutingDataSource.java:95)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:139)
	at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:380)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:228)
	... 33 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.postgresql.core.PGStream.<init>(PGStream.java:70)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:91)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	... 48 more",ERROR,,scheduled-pending-search-items-recover-1,08/09/2019 21:29:40
,org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler,backgrounder_node1-1.log,1080,"Unexpected error occurred in scheduled task.
javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: Could not open connection
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
	at org.hibernate.jpa.internal.QueryImpl.getSingleResult(QueryImpl.java:524)
	at sun.reflect.GeneratedMethodAccessor128.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:375)
	at com.sun.proxy.$Proxy168.getSingleResult(Unknown Source)
	at com.tableausoftware.core.configuration.jpa.GlobalSettingDaoJpa.isSettingLaterThanNow(GlobalSettingDaoJpa.java:90)
	at com.tableausoftware.core.configuration.service.GlobalSettingService.isSettingLaterThanNow(GlobalSettingService.java:236)
	at com.tableausoftware.core.configuration.service.GlobalSettingService$$FastClassBySpringCGLIB$$8b611f6.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:667)
	at com.tableausoftware.core.configuration.service.GlobalSettingService$$EnhancerBySpringCGLIB$$57b08afb.isSettingLaterThanNow(<generated>)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeJobs_aroundBody0(BackgroundJobRunner.java:196)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$AjcClosure1.run(BackgroundJobRunner.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeJobs(BackgroundJobRunner.java:177)
	at com.tableausoftware.backgrounder.config.BackgroundJobRunnerSchedulingConfig.lambda$scheduleTask$0(BackgroundJobRunnerSchedulingConfig.java:42)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.exception.JDBCConnectionException: Could not open connection
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:132)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:235)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.getConnection(LogicalConnectionImpl.java:171)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:63)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:162)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:186)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:160)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1884)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1861)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1838)
	at org.hibernate.loader.Loader.doQuery(Loader.java:909)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:354)
	at org.hibernate.loader.Loader.doList(Loader.java:2553)
	at org.hibernate.loader.Loader.doList(Loader.java:2539)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2369)
	at org.hibernate.loader.Loader.list(Loader.java:2364)
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:353)
	at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:1873)
	at org.hibernate.internal.AbstractSessionImpl.list(AbstractSessionImpl.java:311)
	at org.hibernate.internal.SQLQueryImpl.list(SQLQueryImpl.java:141)
	at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:573)
	at org.hibernate.jpa.internal.QueryImpl.getSingleResult(QueryImpl.java:495)
	... 26 more
Caused by: org.postgresql.util.PSQLException: Connection to localhost:8060 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:280)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:454)
	at org.postgresql.Driver.connect(Driver.java:256)
	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:39)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:256)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at org.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:134)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1533)
	at com.tableausoftware.config.WorkgroupRoutingDataSource.getConnection(WorkgroupRoutingDataSource.java:95)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:139)
	at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:380)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:228)
	... 46 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.postgresql.core.PGStream.<init>(PGStream.java:70)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:91)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	... 61 more",ERROR,,scheduled-background-job-runner-1,08/09/2019 21:29:41
,com.tableausoftware.newrelic.jmx.JMXClient,backgrounder_node1-1.log,1361,"Exception in loading app_name from Newrelic.yml file, NR thread interruptted: null",ERROR,,scheduled-schedule-runner-1,08/09/2019 21:40:38
,com.tableausoftware.newrelic.jmx.JMXClient,backgrounder_node1-1.log,1362,Exception while loading: null,ERROR,,scheduled-schedule-runner-1,08/09/2019 21:40:38
,com.tableausoftware.newrelic.jmx.JMXClient,backgrounder_node1-1.log,1363,CachedSupplier is empty.,ERROR,,scheduled-schedule-runner-1,08/09/2019 21:40:38
199,com.tableausoftware.model.workgroup.extracts.HyperEngineWrapper,backgrounder_node1-1.log,1466,"event=hyperEngineWrapper.refreshExtracts.error totalTime=0.25 resourceType=Workbook resourceId=3 extractsDescriptor={F98E9821-AACE-4288-ABA5-B97AEB67C02F} errorMessage=""The directory is missing or has been moved: C:/Users/Administrator/Desktop/autotel-shared-car-locations\n\n""
com.tableausoftware.nativeapi.exceptions.DataSourceException: The directory is missing or has been moved: C:/Users/Administrator/Desktop/autotel-shared-car-locations


	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.tableausoftware.nativeapi.serialization.ExceptionMapper.mapTableauException(ExceptionMapper.java:111)
	at com.tableausoftware.nativeapi.serialization.ExceptionMapper.mapVizqlWorkerException(ExceptionMapper.java:57)
	at com.tableausoftware.nativeapi.serialization.ExceptionMapper.mapVizqlWorkerException(ExceptionMapper.java:74)
	at com.tableausoftware.nativeapi.transport.VizqlWorkerJNI.VizqlWorkerDispatchRpcCall(Native Method)
	at com.tableausoftware.nativeapi.transport.InProcVizqlWorkerClient.invoke(InProcVizqlWorkerClient.java:103)
	at com.tableausoftware.nativeapi.transport.InProcVizqlWorkerClient.invokeCommandInternal(InProcVizqlWorkerClient.java:131)
	at com.tableausoftware.nativeapi.AutowiredVizqlWorker.invokeCommandInternal(AutowiredVizqlWorker.java:39)
	at com.tableausoftware.nativeapi.commands.ExtractsCommands.refreshWorkbookExtracts(ExtractsCommands.java:536)
	at com.tableausoftware.model.workgroup.extracts.HyperEngineWrapper.refreshExtracts_aroundBody8(HyperEngineWrapper.java:408)
	at com.tableausoftware.model.workgroup.extracts.HyperEngineWrapper$AjcClosure9.run(HyperEngineWrapper.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.utils.logging.StructuredLoggerAspect.runWithLogging(StructuredLoggerAspect.java:49)
	at com.tableausoftware.model.workgroup.extracts.HyperEngineWrapper.refreshExtracts(HyperEngineWrapper.java:401)
	at com.tableausoftware.model.workgroup.extracts.ExtractActionService$SessionAction.doNativeApiWorkbookExtractAction(ExtractActionService.java:2150)
	at com.tableausoftware.model.workgroup.extracts.ExtractActionService$SessionAction.access$800(ExtractActionService.java:1684)
	at com.tableausoftware.model.workgroup.extracts.ExtractActionService.refreshExtractsForWorkbook(ExtractActionService.java:1001)
	at com.tableausoftware.model.workgroup.extracts.ExtractActionService.refreshExtractsForWorkbook(ExtractActionService.java:120)
	at com.tableausoftware.model.workgroup.workers.ExtractsWorker.refreshWorkbook(ExtractsWorker.java:871)
	at com.tableausoftware.model.workgroup.workers.ExtractsWorker.executeWithDataengine(ExtractsWorker.java:614)
	at com.tableausoftware.model.workgroup.workers.RefreshExtractsWorker.executeWithDataengine_aroundBody0(RefreshExtractsWorker.java:103)
	at com.tableausoftware.model.workgroup.workers.RefreshExtractsWorker$AjcClosure1.run(RefreshExtractsWorker.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.model.workgroup.workers.RefreshExtractsWorker.executeWithDataengine(RefreshExtractsWorker.java:103)
	at com.tableausoftware.model.workgroup.workers.DataengineDependentWorker.execute(DataengineDependentWorker.java:87)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable.executeWithWorker(BackgroundJobRunner.java:811)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable.call_aroundBody0(BackgroundJobRunner.java:763)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable$AjcClosure1.run(BackgroundJobRunner.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable.call(BackgroundJobRunner.java:758)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable.call(BackgroundJobRunner.java:745)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)",ERROR,Default,pool-12-thread-1,08/09/2019 21:46:10
199,com.tableausoftware.backgrounder.runner.BackgroundJobRunner,backgrounder_node1-1.log,1561,"Error executing background job: RefreshExtracts
java.util.concurrent.ExecutionException: com.tableausoftware.nativeapi.exceptions.DataSourceException: The directory is missing or has been moved: C:/Users/Administrator/Desktop/autotel-shared-car-locations


	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeNextJob_aroundBody2(BackgroundJobRunner.java:279)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$AjcClosure3.run(BackgroundJobRunner.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeNextJob(BackgroundJobRunner.java:216)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeJobs_aroundBody0(BackgroundJobRunner.java:201)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$AjcClosure1.run(BackgroundJobRunner.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeJobs(BackgroundJobRunner.java:177)
	at com.tableausoftware.backgrounder.config.BackgroundJobRunnerSchedulingConfig.lambda$scheduleTask$0(BackgroundJobRunnerSchedulingConfig.java:42)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.tableausoftware.nativeapi.exceptions.DataSourceException: The directory is missing or has been moved: C:/Users/Administrator/Desktop/autotel-shared-car-locations


	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.tableausoftware.nativeapi.serialization.ExceptionMapper.mapTableauException(ExceptionMapper.java:111)
	at com.tableausoftware.nativeapi.serialization.ExceptionMapper.mapVizqlWorkerException(ExceptionMapper.java:57)
	at com.tableausoftware.nativeapi.serialization.ExceptionMapper.mapVizqlWorkerException(ExceptionMapper.java:74)
	at com.tableausoftware.nativeapi.transport.VizqlWorkerJNI.VizqlWorkerDispatchRpcCall(Native Method)
	at com.tableausoftware.nativeapi.transport.InProcVizqlWorkerClient.invoke(InProcVizqlWorkerClient.java:103)
	at com.tableausoftware.nativeapi.transport.InProcVizqlWorkerClient.invokeCommandInternal(InProcVizqlWorkerClient.java:131)
	at com.tableausoftware.nativeapi.AutowiredVizqlWorker.invokeCommandInternal(AutowiredVizqlWorker.java:39)
	at com.tableausoftware.nativeapi.commands.ExtractsCommands.refreshWorkbookExtracts(ExtractsCommands.java:536)
	at com.tableausoftware.model.workgroup.extracts.HyperEngineWrapper.refreshExtracts_aroundBody8(HyperEngineWrapper.java:408)
	at com.tableausoftware.model.workgroup.extracts.HyperEngineWrapper$AjcClosure9.run(HyperEngineWrapper.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.utils.logging.StructuredLoggerAspect.runWithLogging(StructuredLoggerAspect.java:49)
	at com.tableausoftware.model.workgroup.extracts.HyperEngineWrapper.refreshExtracts(HyperEngineWrapper.java:401)
	at com.tableausoftware.model.workgroup.extracts.ExtractActionService$SessionAction.doNativeApiWorkbookExtractAction(ExtractActionService.java:2150)
	at com.tableausoftware.model.workgroup.extracts.ExtractActionService$SessionAction.access$800(ExtractActionService.java:1684)
	at com.tableausoftware.model.workgroup.extracts.ExtractActionService.refreshExtractsForWorkbook(ExtractActionService.java:1001)
	at com.tableausoftware.model.workgroup.extracts.ExtractActionService.refreshExtractsForWorkbook(ExtractActionService.java:120)
	at com.tableausoftware.model.workgroup.workers.ExtractsWorker.refreshWorkbook(ExtractsWorker.java:871)
	at com.tableausoftware.model.workgroup.workers.ExtractsWorker.executeWithDataengine(ExtractsWorker.java:614)
	at com.tableausoftware.model.workgroup.workers.RefreshExtractsWorker.executeWithDataengine_aroundBody0(RefreshExtractsWorker.java:103)
	at com.tableausoftware.model.workgroup.workers.RefreshExtractsWorker$AjcClosure1.run(RefreshExtractsWorker.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.model.workgroup.workers.RefreshExtractsWorker.executeWithDataengine(RefreshExtractsWorker.java:103)
	at com.tableausoftware.model.workgroup.workers.DataengineDependentWorker.execute(DataengineDependentWorker.java:87)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable.executeWithWorker(BackgroundJobRunner.java:811)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable.call_aroundBody0(BackgroundJobRunner.java:763)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable$AjcClosure1.run(BackgroundJobRunner.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable.call(BackgroundJobRunner.java:758)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$ExecuteJobImplCallable.call(BackgroundJobRunner.java:745)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more",ERROR,Default,scheduled-background-job-runner-1,08/09/2019 21:46:10
199,com.tableausoftware.backgrounder.runner.BackgroundJobRunner,backgrounder_node1-1.log,1634,"Send notification failed
java.lang.IllegalArgumentException: from email address """" not in expected format
	at com.tableausoftware.domain.notifications.email.EmailAddress.<init>(EmailAddress.java:47)
	at com.tableausoftware.domain.notifications.email.EmailWriterFactory.newAddress(EmailWriterFactory.java:16)
	at com.tableausoftware.model.workgroup.workers.ExtractsWorker.sendNotificationEmail(ExtractsWorker.java:442)
	at com.tableausoftware.model.workgroup.workers.ExtractsWorker.sendNotificationToObjectOwner(ExtractsWorker.java:425)
	at com.tableausoftware.model.workgroup.workers.ExtractsWorker.sendNotificationOnFailure(ExtractsWorker.java:341)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.onExecutionFailure_aroundBody4(BackgroundJobRunner.java:727)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$AjcClosure5.run(BackgroundJobRunner.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.onExecutionFailure(BackgroundJobRunner.java:727)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeNextJob_aroundBody2(BackgroundJobRunner.java:341)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$AjcClosure3.run(BackgroundJobRunner.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeNextJob(BackgroundJobRunner.java:216)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeJobs_aroundBody0(BackgroundJobRunner.java:201)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner$AjcClosure1.run(BackgroundJobRunner.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.tableausoftware.instrumentation.InstrumentedMethod.instrumentInvocation(InstrumentedMethod.java:73)
	at com.tableausoftware.instrumentation.InstrumentationAspect.aroundAnnotatedMethod(InstrumentationAspect.java:60)
	at com.tableausoftware.backgrounder.runner.BackgroundJobRunner.executeJobs(BackgroundJobRunner.java:177)
	at com.tableausoftware.backgrounder.config.BackgroundJobRunnerSchedulingConfig.lambda$scheduleTask$0(BackgroundJobRunnerSchedulingConfig.java:42)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.mail.internet.AddressException: Illegal address in string ``''
	at javax.mail.internet.InternetAddress.<init>(InternetAddress.java:118)
	at com.tableausoftware.domain.notifications.email.EmailAddress.<init>(EmailAddress.java:38)
	... 31 more",ERROR,Default,scheduled-background-job-runner-1,08/09/2019 21:46:11
201,com.tableausoftware.domain.materializedviews.service.MaterializedViewService,backgrounder_node1-1.log,1711,tableau-materialized-views: materialization for objectId 3 from siteId 1 due to trigger ExtractRefreshed should not happen Skipping job submission,ERROR,Default,pool-12-thread-1,08/09/2019 21:50:17
